language: c
matrix:
  include:
    - name: gcc
      os: linux
      script: cmake .. && make
    - name: osx clang
      os: osx
      script: cmake .. && make
    - name: linux emscripten
      os: linux
      install:
        - wget https://s3.amazonaws.com/mozilla-games/emscripten/releases/emsdk-portable.tar.gz
        - tar xvzf emsdk-portable.tar.gz
        - cd emsdk-portable
        - ./emsdk install latest
        - ./emsdk activate latest
        - source ./emsdk_env.sh
        - cd ..
      script: cmake .. -DCMAKE_C_COMPILER=$EMSCRIPTEN/emcc && make
os:
  - linux
  - osx
addons:
  homebrew:
    packages:
    - flex
  apt:
    packages:
    - flex
before_script:
  - mkdir build
  - cd build

